version: '3'
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx_conf:/data/nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: nginx:1.13
    network_mode: "host"
    restart: always
    container_name: nginx
    volumes:
      - ./nginx_conf/:/etc/nginx/conf.d
      # - static:/static
      # - ./media:/media
volumes:
  static:
  redisdata: